// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

// Import user types
import { StorageTransaction } from "../common.sol";

struct TribeStorageTransactionData {
  address tribesmenAddress;
  uint256 inventoryItemId;
  uint256 inventoryItemAmount;
  uint256 smartStorageUnitId;
  uint256 timestamp;
  StorageTransaction transactionType;
}

library TribeStorageTransaction {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "AWAR", name: "TribeStorageTran", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x74624157415200000000000000000000547269626553746f726167655472616e);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0095060014202020200100000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (uint256)
  Schema constant _keySchema = Schema.wrap(0x002001001f000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (address, uint256, uint256, uint256, uint256, uint8)
  Schema constant _valueSchema = Schema.wrap(0x00950600611f1f1f1f0000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "transactionId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](6);
    fieldNames[0] = "tribesmenAddress";
    fieldNames[1] = "inventoryItemId";
    fieldNames[2] = "inventoryItemAmount";
    fieldNames[3] = "smartStorageUnitId";
    fieldNames[4] = "timestamp";
    fieldNames[5] = "transactionType";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get tribesmenAddress.
   */
  function getTribesmenAddress(uint256 transactionId) internal view returns (address tribesmenAddress) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Get tribesmenAddress.
   */
  function _getTribesmenAddress(uint256 transactionId) internal view returns (address tribesmenAddress) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (address(bytes20(_blob)));
  }

  /**
   * @notice Set tribesmenAddress.
   */
  function setTribesmenAddress(uint256 transactionId, address tribesmenAddress) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((tribesmenAddress)), _fieldLayout);
  }

  /**
   * @notice Set tribesmenAddress.
   */
  function _setTribesmenAddress(uint256 transactionId, address tribesmenAddress) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((tribesmenAddress)), _fieldLayout);
  }

  /**
   * @notice Get inventoryItemId.
   */
  function getInventoryItemId(uint256 transactionId) internal view returns (uint256 inventoryItemId) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get inventoryItemId.
   */
  function _getInventoryItemId(uint256 transactionId) internal view returns (uint256 inventoryItemId) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set inventoryItemId.
   */
  function setInventoryItemId(uint256 transactionId, uint256 inventoryItemId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((inventoryItemId)), _fieldLayout);
  }

  /**
   * @notice Set inventoryItemId.
   */
  function _setInventoryItemId(uint256 transactionId, uint256 inventoryItemId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((inventoryItemId)), _fieldLayout);
  }

  /**
   * @notice Get inventoryItemAmount.
   */
  function getInventoryItemAmount(uint256 transactionId) internal view returns (uint256 inventoryItemAmount) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get inventoryItemAmount.
   */
  function _getInventoryItemAmount(uint256 transactionId) internal view returns (uint256 inventoryItemAmount) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set inventoryItemAmount.
   */
  function setInventoryItemAmount(uint256 transactionId, uint256 inventoryItemAmount) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((inventoryItemAmount)), _fieldLayout);
  }

  /**
   * @notice Set inventoryItemAmount.
   */
  function _setInventoryItemAmount(uint256 transactionId, uint256 inventoryItemAmount) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((inventoryItemAmount)), _fieldLayout);
  }

  /**
   * @notice Get smartStorageUnitId.
   */
  function getSmartStorageUnitId(uint256 transactionId) internal view returns (uint256 smartStorageUnitId) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get smartStorageUnitId.
   */
  function _getSmartStorageUnitId(uint256 transactionId) internal view returns (uint256 smartStorageUnitId) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 3, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set smartStorageUnitId.
   */
  function setSmartStorageUnitId(uint256 transactionId, uint256 smartStorageUnitId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((smartStorageUnitId)), _fieldLayout);
  }

  /**
   * @notice Set smartStorageUnitId.
   */
  function _setSmartStorageUnitId(uint256 transactionId, uint256 smartStorageUnitId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    StoreCore.setStaticField(_tableId, _keyTuple, 3, abi.encodePacked((smartStorageUnitId)), _fieldLayout);
  }

  /**
   * @notice Get timestamp.
   */
  function getTimestamp(uint256 transactionId) internal view returns (uint256 timestamp) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get timestamp.
   */
  function _getTimestamp(uint256 transactionId) internal view returns (uint256 timestamp) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 4, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set timestamp.
   */
  function setTimestamp(uint256 transactionId, uint256 timestamp) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((timestamp)), _fieldLayout);
  }

  /**
   * @notice Set timestamp.
   */
  function _setTimestamp(uint256 transactionId, uint256 timestamp) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    StoreCore.setStaticField(_tableId, _keyTuple, 4, abi.encodePacked((timestamp)), _fieldLayout);
  }

  /**
   * @notice Get transactionType.
   */
  function getTransactionType(uint256 transactionId) internal view returns (StorageTransaction transactionType) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return StorageTransaction(uint8(bytes1(_blob)));
  }

  /**
   * @notice Get transactionType.
   */
  function _getTransactionType(uint256 transactionId) internal view returns (StorageTransaction transactionType) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 5, _fieldLayout);
    return StorageTransaction(uint8(bytes1(_blob)));
  }

  /**
   * @notice Set transactionType.
   */
  function setTransactionType(uint256 transactionId, StorageTransaction transactionType) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked(uint8(transactionType)), _fieldLayout);
  }

  /**
   * @notice Set transactionType.
   */
  function _setTransactionType(uint256 transactionId, StorageTransaction transactionType) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    StoreCore.setStaticField(_tableId, _keyTuple, 5, abi.encodePacked(uint8(transactionType)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(uint256 transactionId) internal view returns (TribeStorageTransactionData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(uint256 transactionId) internal view returns (TribeStorageTransactionData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    uint256 transactionId,
    address tribesmenAddress,
    uint256 inventoryItemId,
    uint256 inventoryItemAmount,
    uint256 smartStorageUnitId,
    uint256 timestamp,
    StorageTransaction transactionType
  ) internal {
    bytes memory _staticData = encodeStatic(
      tribesmenAddress,
      inventoryItemId,
      inventoryItemAmount,
      smartStorageUnitId,
      timestamp,
      transactionType
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    uint256 transactionId,
    address tribesmenAddress,
    uint256 inventoryItemId,
    uint256 inventoryItemAmount,
    uint256 smartStorageUnitId,
    uint256 timestamp,
    StorageTransaction transactionType
  ) internal {
    bytes memory _staticData = encodeStatic(
      tribesmenAddress,
      inventoryItemId,
      inventoryItemAmount,
      smartStorageUnitId,
      timestamp,
      transactionType
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(uint256 transactionId, TribeStorageTransactionData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.tribesmenAddress,
      _table.inventoryItemId,
      _table.inventoryItemAmount,
      _table.smartStorageUnitId,
      _table.timestamp,
      _table.transactionType
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(uint256 transactionId, TribeStorageTransactionData memory _table) internal {
    bytes memory _staticData = encodeStatic(
      _table.tribesmenAddress,
      _table.inventoryItemId,
      _table.inventoryItemAmount,
      _table.smartStorageUnitId,
      _table.timestamp,
      _table.transactionType
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  )
    internal
    pure
    returns (
      address tribesmenAddress,
      uint256 inventoryItemId,
      uint256 inventoryItemAmount,
      uint256 smartStorageUnitId,
      uint256 timestamp,
      StorageTransaction transactionType
    )
  {
    tribesmenAddress = (address(Bytes.getBytes20(_blob, 0)));

    inventoryItemId = (uint256(Bytes.getBytes32(_blob, 20)));

    inventoryItemAmount = (uint256(Bytes.getBytes32(_blob, 52)));

    smartStorageUnitId = (uint256(Bytes.getBytes32(_blob, 84)));

    timestamp = (uint256(Bytes.getBytes32(_blob, 116)));

    transactionType = StorageTransaction(uint8(Bytes.getBytes1(_blob, 148)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (TribeStorageTransactionData memory _table) {
    (
      _table.tribesmenAddress,
      _table.inventoryItemId,
      _table.inventoryItemAmount,
      _table.smartStorageUnitId,
      _table.timestamp,
      _table.transactionType
    ) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(uint256 transactionId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(uint256 transactionId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    address tribesmenAddress,
    uint256 inventoryItemId,
    uint256 inventoryItemAmount,
    uint256 smartStorageUnitId,
    uint256 timestamp,
    StorageTransaction transactionType
  ) internal pure returns (bytes memory) {
    return
      abi.encodePacked(
        tribesmenAddress,
        inventoryItemId,
        inventoryItemAmount,
        smartStorageUnitId,
        timestamp,
        transactionType
      );
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    address tribesmenAddress,
    uint256 inventoryItemId,
    uint256 inventoryItemAmount,
    uint256 smartStorageUnitId,
    uint256 timestamp,
    StorageTransaction transactionType
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(
      tribesmenAddress,
      inventoryItemId,
      inventoryItemAmount,
      smartStorageUnitId,
      timestamp,
      transactionType
    );

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(uint256 transactionId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = bytes32(uint256(transactionId));

    return _keyTuple;
  }
}
