// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { PingTest, PingTestData } from "./tables/PingTest.sol";
import { TribeStorageTransaction, TribeStorageTransactionData } from "./tables/TribeStorageTransaction.sol";
