// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { TribeStorageTransaction, TribeStorageTransactionData } from "./tables/TribeStorageTransaction.sol";
import { TribePackage, TribePackageData } from "./tables/TribePackage.sol";
import { TribePackageEntries, TribePackageEntriesData } from "./tables/TribePackageEntries.sol";
