// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Package } from "../../systems/types.sol";

/**
 * @title ITribeDispenserSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITribeDispenserSystem {
  function AWAR__registerPackage(
    uint256 smartStorageUnitId,
    string memory packageName,
    Package memory package
  ) external;

  function AWAR__getPackage(uint256 packageId) external view returns (Package memory);

  function AWAR__renamePackage(uint256 packageId, string memory newPackageName) external;

  function AWAR__unregisterPackage(uint256 packageId) external;

  function AWAR__dispensePackageMaterials(uint256 smartStorageUnitId, uint256 packageId, uint256 quantity) external;
}
